### ISSUE TITLE
Barycentric interpolation with interval arithmetic

### ISSUE THREAD

**Issue by ArjunNarayanan** [dawbarton/BarycentricInterpolation.jl#3]
First off, thanks for your great little package!

I am interested in interval arithmetic on polynomial spaces. I am using [IntervalArithmetic.jl](https://github.com/JuliaIntervals/IntervalArithmetic.jl) for this.

When I tried to obtain the `interpolation_matrix` of polynomial, I ran into some issues. As an example,

```
using IntervalArithmetic
using BarycentricInterpolation

int = Interval(0.1,0.2)
P = Equispaced{1}()
vals = interpolation_matrix(P,int)
MethodError: no method matching Float64(::Interval{Float64})
```

The line that raises the error is,

https://github.com/dawbarton/BarycentricInterpolation.jl/blob/e90ec00607552b2a8966feee3dcb3a7d4f5809d3/src/BarycentricInterpolation.jl#L136

I think it would be better to template this function on the type of the evaluation points `x` rather than the type of the polynomial coefficients as it would allow to dispatch on other `Number` types.

https://github.com/dawbarton/BarycentricInterpolation.jl/blob/e90ec00607552b2a8966feee3dcb3a7d4f5809d3/src/BarycentricInterpolation.jl#L130

Happy to work on a pull request for this, just wanted to hear your thoughts!

**Comment by ArjunNarayanan** [comment]
Ah, it seems like there are other more complex issues with using interval arithmetic in combination with barycentric interpolation.

For example, if an interval contains a `node`, then the output interval can be arbitrarily loose `[0,∞]`,

the main issue being handling the equivalent of this check for intervals,

https://github.com/dawbarton/BarycentricInterpolation.jl/blob/e90ec00607552b2a8966feee3dcb3a7d4f5809d3/src/BarycentricInterpolation.jl#L140

**Comment by dawbarton** [comment]
Thanks for the interest. As you've discovered, I'm not sure that the barycentric formalism is best for interval arithmetic (at least not for intervals in the representation points). For intervals in the data (y) values it should be fine though.

**Comment by dawbarton** [comment]
If you do manage to work out how it should be done with interval arithmetic, do feel free to submit a PR!

**Comment by ArjunNarayanan** [comment]
Thanks for your reply!

I'll investigate if there are any methods available.
